name: 🐞 Bug Report
description: Report a bug, glitch, or unintended behavior.
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below so we can identify and resolve the issue as quickly as possible. 🚧

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Provide a clear and concise explanation of the issue.
      placeholder: |
        Example:
        - "The bot crashes when I run command X."
        - "Clicking button Y does nothing."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps we can follow to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. Error appears
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
      placeholder: |
        Example:
        - "The command should return a success message."
        - "The page should load without errors."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: |
        Example:
        - "The bot responded with an error."
        - "The UI froze and did not respond."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Visual Evidence (optional)
      description: If applicable, drag and drop images, logs, or error messages.
      placeholder: "Attach logs, screenshots, or console output here."
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: System or app context where the bug occurred.
      placeholder: |
        Example:
        - OS: Windows 11
        - Browser: Chrome 120
        - Node: v18
        - App Version: 1.2.0
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How serious is this issue?
      options:
        - Critical (system broken, major impact)
        - High (feature broken, large impact)
        - Moderate (bug affects usage)
        - Low (minor bug, does not affect functionality)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any extra information that may assist in troubleshooting.
      placeholder: "Any extra notes, related tickets, or observations."
    validations:
      required: false
