name: 🐞 Bug Report
description: Report a bug, glitch, or unintended behavior.
title: "[Bug]: "
labels: ["bug"]
projects: ["Streamers Hub"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below so we can identify and resolve the issue as quickly as possible. 🚧
  - type: dropdown
    id: service
    attributes:
      label: Which service does the bug relate to?
      multiple: false
      options:
        - ◾️ Roblox
        - 🤖 Discord Bots
        - 🗃️ Discord Channel Access
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How serious is this issue?
      options:
        - "Critical (system broken, major impact)"
        - "High (feature broken, large impact)"
        - "Moderate (bug affects usage)"
        - "Low (minor bug, does not affect functionality)"
    validations:
      required: true

  - type: textarea
    id: explanation
    attributes:
      label: Breif Explanation
      description: Provide a clear and concise explanation of the issue.
      placeholder: |
        Example:
        - "The bot crashes when I run command X."
        - "Clicking button Y does nothing."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce (if applicable)
      description: List the steps we can follow to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. Error appears
    validations:
      required: false

  - type: textarea
    id: media
    attributes:
      label: Relevant Media: Screenshots / Visual Evidence (optional)
      description: If applicable, drag and drop images, logs, or error messages.
      placeholder: "Attach logs, screenshots, or console output here."
    validations:
      required: false
