name: Apply Issue Type Label
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  apply_label:
    runs-on: ubuntu-latest
    steps:

      - name: Add Feature Request label
        if: contains(toJson(github.event.issue.body), 'Feature Request')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: Feature Request

      - name: Add Improvement label
        if: contains(toJson(github.event.issue.body), 'Improvement')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: Improvement
