name: Issue → Project status sync

on:
  issues:
    types: [opened, reopened, assigned, closed]

jobs:
  sync_issue_to_project:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      projects: write

    steps:
      - name: Sync status to Project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const PROJECT_ID = "PVT_kwHODJwWRs4BGPB1";
            const STATUS_FIELD_ID = "PVTSSF_lAHOD
