name: 🧭 Issue → Project Status Sync

on:
  issues:
    types: [opened, edited, assigned, unassigned, closed, reopened]

permissions:
  issues: write
  projects: write

jobs:
  project_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const PROJECT_ID = "PVT_kwHODJwWRs4BGPB1";
            const STATUS_FIELD_ID = "PVTSSF_lAHODJwWRs4BGPB1zg3VyXg";
            const OPT = {
              ENTRY: "f75ad846",
              IN_PROGRESS: "47fc9ee4",
              DONE_COMPLETED: "98236657",
              DONE_NOT_PLANNED: "13d5fa23",
              DONE_DUPLICATE: "8356ef49"
            };

            const issueNodeId = context.payload.issue.node_id;
            const action = context.payload.action;

            // Give GitHub time to auto-add the issue to the project before querying
            const sleep = ms => new Promise(r => setTimeout(r, ms));
            await sleep(1500);

            // ✅ FIXED QUERY — uses projectsV2, not projectItemsV2
            const query = `
              query($issueId: ID!) {
                node(id:$issueId) {
                  ... on Issue {
                    projectsV2(first:20) {
                      nodes { id project { id } }
                    }
                  }
                }
              }`;

            const data = await github.graphql(query, { issueId: issueNodeId });

            // ✅ FIXED LOOKUP — uses projectsV2
            const nodes = data?.node?.projectsV2?.nodes || [];
            const item = nodes.find(n => n.project.id === PROJECT_ID);
            if (!item) {
              core.info("Project item not found yet — skipping.");
              return;
            }

            async function setStatus(optionId) {
              const mutation = `
                mutation($project:ID!,$item:ID!,$field:ID!,$opt:String!) {
                  updateProjectV2ItemFieldValue(input:{
                    projectId:$project,
                    itemId:$item,
                    fieldId:$field,
                    value:{singleSelectOptionId:$opt}
                  }) {
                    projectV2Item { id }
                  }
                }`;
              await github.graphql(mutation, {
                project: PROJECT_ID,
                item: item.id,
                field: STATUS_FIELD_ID,
                opt: optionId
              });
            }

            // ✅ Event → Status logic
            if (action === "opened") {
              await setStatus(OPT.ENTRY);
              return;
            }

            if (action === "assigned" && context.payload.assignee) {
              await setStatus(OPT.IN_PROGRESS);
              return;
            }

            if (action === "reopened") {
              await setStatus(OPT.ENTRY);
              return;
            }

            if (action === "closed") {
              const reason = (context.payload.issue.state_reason || "").toLowerCase();
              if (reason === "not_planned") return setStatus(OPT.DONE_NOT_PLANNED);
              if (reason === "duplicate") return setStatus(OPT.DONE_DUPLICATE);
              return setStatus(OPT.DONE_COMPLETED);
            }
